# Override the port Tomcat listens on
server:
  port: 9001

# Customize log levels
logging:
  level:
    com:
      giocosmiano: DEBUG

# enable actuator endpoints
#endpoints.autoconfig.enabled=true
#endpoints.beans.enabled=true
#endpoints.configprops.enabled=true
#endpoints.env.enabled=true
#endpoints.health.enabled=true
#endpoints.info.enabled=true
#endpoints.metrics.enabled=true
#endpoints.mappings.enabled=true
#endpoints.trace.enabled=true
