# Override the port Tomcat listens on
server:
  port: 9006

# Customize log levels
logging:
  level:
    reactor:
      core: TRACE
      util: TRACE
    org:
      springframework:
        data: TRACE
    io:
      netty: DEBUG
      reactor: DEBUG
    com:
      giocosmiano: DEBUG

# enable actuator endpoints
#endpoints.autoconfig.enabled=true
#endpoints.beans.enabled=true
#endpoints.configprops.enabled=true
#endpoints.env.enabled=true
#endpoints.health.enabled=true
#endpoints.info.enabled=true
#endpoints.metrics.enabled=true
#endpoints.mappings.enabled=true
#endpoints.trace.enabled=true

# To connect IDE to a remotely running application and push code changes over the wire, allowing to automatically make mods and test them immediately
spring:
  devtools:
    remote:
      secret: ch05-developer-tools-for-spring-boot
    restart:
      poll-interval: 4000

# http://localhost:9006/actuator
management:
  endpoints:
# exposing endpoints over http
    web:
      exposure:
        include: "*"
# exposing endpoints over jmx
#    jmx:
#      exposure:
#        include: "*"

